module.exports = [
  {
    title: "Senior Developer",
    company: "Thiel LLC",
    jobLocation: "Raminho",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-03-29T06:09:22Z",
  },
  {
    title: "Engineer II",
    company: "Boyle-Roberts",
    jobLocation: "Jingyang",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2023-10-18T23:44:45Z",
  },
  {
    title: "Electrical Engineer",
    company: "Schulist Inc",
    jobLocation: "Telmin Suma",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-10-03T13:04:47Z",
  },
  {
    title: "Internal Auditor",
    company: "Wunsch-Botsford",
    jobLocation: "Starobin",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2023-11-23T13:08:09Z",
  },
  {
    title: "Dental Hygienist",
    company: "Crona, Prosacco and Rohan",
    jobLocation: "San Antonio",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-08-27T03:57:32Z",
  },
  {
    title: "Research Assistant II",
    company: "Schinner, Lubowitz and Monahan",
    jobLocation: "Brwinów",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-06-27T01:58:40Z",
  },
  {
    title: "Accountant IV",
    company: "Champlin, Bahringer and Stanton",
    jobLocation: "Yanzhao",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2023-12-26T13:19:57Z",
  },
  {
    title: "Biostatistician III",
    company: "Kilback Inc",
    jobLocation: "Walnut Grove",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-08-17T03:32:06Z",
  },
  {
    title: "Office Assistant I",
    company: "Leannon LLC",
    jobLocation: "Tost",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-03-15T07:45:42Z",
  },
  {
    title: "Cost Accountant",
    company: "Jenkins, Lindgren and Homenick",
    jobLocation: "Mancilang",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2024-05-11T04:45:37Z",
  },
  {
    title: "Associate Professor",
    company: "Witting-Batz",
    jobLocation: "Sindanghayu",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-09-19T17:20:38Z",
  },
  {
    title: "Analog Circuit Design manager",
    company: "Kutch LLC",
    jobLocation: "Issia",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-09-09T14:43:31Z",
  },
  {
    title: "Technical Writer",
    company: "Douglas LLC",
    jobLocation: "Saryözek",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2023-10-27T21:08:47Z",
  },
  {
    title: "Food Chemist",
    company: "Swift-Beier",
    jobLocation: "Levandeira",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2023-11-09T20:59:43Z",
  },
  {
    title: "Research Assistant IV",
    company: "Rice and Sons",
    jobLocation: "Hwado",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-02-13T03:01:40Z",
  },
  {
    title: "Software Test Engineer IV",
    company: "Reilly, Batz and Muller",
    jobLocation: "Comalapa",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2023-12-12T23:51:12Z",
  },
  {
    title: "Automation Specialist II",
    company: "Mante-Gutkowski",
    jobLocation: "Nova Friburgo",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2023-12-18T23:21:58Z",
  },
  {
    title: "Automation Specialist II",
    company: "Gleason-Jaskolski",
    jobLocation: "Askeaton",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2023-11-20T09:57:35Z",
  },
  {
    title: "Information Systems Manager",
    company: "Grady, Fahey and Schmeler",
    jobLocation: "Behābād",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2023-11-28T23:51:17Z",
  },
  {
    title: "Staff Accountant II",
    company: "Parker, Legros and Koelpin",
    jobLocation: "Sacramento",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-10-02T09:25:15Z",
  },
  {
    title: "Librarian",
    company: "Osinski and Sons",
    jobLocation: "Duoxiang",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2024-10-08T12:54:23Z",
  },
  {
    title: "Business Systems Development Analyst",
    company: "Grimes LLC",
    jobLocation: "Bandar-e Torkaman",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2023-11-02T14:11:23Z",
  },
  {
    title: "Design Engineer",
    company: "Runte-Kertzmann",
    jobLocation: "Caen",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-08-11T21:51:19Z",
  },
  {
    title: "Executive Secretary",
    company: "Dietrich, Keeling and Sawayn",
    jobLocation: "Itambé",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2023-12-27T14:54:20Z",
  },
  {
    title: "Occupational Therapist",
    company: "Schmeler-Rogahn",
    jobLocation: "Sanxing",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2023-10-26T22:44:02Z",
  },
  {
    title: "Payment Adjustment Coordinator",
    company: "Braun LLC",
    jobLocation: "Otan Aiyegbaju",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-06-28T01:39:04Z",
  },
  {
    title: "Programmer II",
    company: "Hane, Morar and Herman",
    jobLocation: "Novotroitsk",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2024-08-07T17:01:52Z",
  },
  {
    title: "Associate Professor",
    company: "Stamm LLC",
    jobLocation: "Calvaria de Baixo",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2024-04-19T20:45:19Z",
  },
  {
    title: "Mechanical Systems Engineer",
    company: "Miller, Cronin and Collier",
    jobLocation: "Póvoa de Santo António",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-09-24T11:26:03Z",
  },
  {
    title: "Editor",
    company: "Crona, Crooks and Mayer",
    jobLocation: "Frederiksberg",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-10-14T12:31:53Z",
  },
  {
    title: "Account Representative III",
    company: "Streich, Barton and Rosenbaum",
    jobLocation: "Tawaramoto",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2023-11-09T20:33:49Z",
  },
  {
    title: "Accountant II",
    company: "Brown, Bayer and Armstrong",
    jobLocation: "Sumurwaru",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2023-12-04T02:17:27Z",
  },
  {
    title: "Cost Accountant",
    company: "Champlin, Aufderhar and Wiegand",
    jobLocation: "Digkilaan",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2023-10-29T11:27:06Z",
  },
  {
    title: "Occupational Therapist",
    company: "Hauck-Heathcote",
    jobLocation: "Saint-Marcellin",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-09-16T02:49:04Z",
  },
  {
    title: "Desktop Support Technician",
    company: "Veum, Nicolas and Johns",
    jobLocation: "Macroom",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-06-11T00:08:28Z",
  },
  {
    title: "Product Engineer",
    company: "Kreiger, Pagac and Bergstrom",
    jobLocation: "Prior Velho",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-06-10T18:16:36Z",
  },
  {
    title: "Graphic Designer",
    company: "Koch, Murphy and Leannon",
    jobLocation: "Cradock",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-10-03T14:23:14Z",
  },
  {
    title: "Professor",
    company: "Bechtelar-Lakin",
    jobLocation: "Yinghai",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-03-28T20:54:15Z",
  },
  {
    title: "Professor",
    company: "Veum-Daugherty",
    jobLocation: "Pandaan",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-01-08T21:57:48Z",
  },
  {
    title: "Environmental Specialist",
    company: "Toy, Yundt and O'Keefe",
    jobLocation: "Qutun",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-07-06T02:36:16Z",
  },
  {
    title: "Senior Financial Analyst",
    company: "Nikolaus Inc",
    jobLocation: "Markala",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-09-19T17:07:23Z",
  },
  {
    title: "Financial Analyst",
    company: "Hauck LLC",
    jobLocation: "Portela",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-08-28T06:39:35Z",
  },
  {
    title: "VP Sales",
    company: "Littel-Feest",
    jobLocation: "Saijō",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2023-12-25T03:23:44Z",
  },
  {
    title: "Office Assistant IV",
    company: "Sawayn, Klocko and Mante",
    jobLocation: "Jihui",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2023-11-12T10:31:41Z",
  },
  {
    title: "Web Designer II",
    company: "Boyer Inc",
    jobLocation: "Undurkhaan",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-08-11T23:11:49Z",
  },
  {
    title: "Safety Technician I",
    company: "Klocko, Willms and Romaguera",
    jobLocation: "Zhoushan",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2023-11-20T19:21:29Z",
  },
  {
    title: "Sales Representative",
    company: "Wunsch Group",
    jobLocation: "Lucerna",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-10-06T02:36:06Z",
  },
  {
    title: "Geological Engineer",
    company: "Farrell, Goldner and Stehr",
    jobLocation: "Pirot",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-06-23T20:52:59Z",
  },
  {
    title: "Structural Analysis Engineer",
    company: "Schuster and Sons",
    jobLocation: "Chunyang",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-08-13T02:45:20Z",
  },
  {
    title: "Accountant II",
    company: "Schamberger, Grant and Graham",
    jobLocation: "Kham Sakae Saeng",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-06-21T00:04:43Z",
  },
  {
    title: "Legal Assistant",
    company: "Murazik-Lebsack",
    jobLocation: "Saue",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-03-08T20:52:01Z",
  },
  {
    title: "Nuclear Power Engineer",
    company: "Ruecker, Jast and Roob",
    jobLocation: "Markaz Bilād aţ Ţa‘ām",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2023-10-28T02:23:01Z",
  },
  {
    title: "Senior Developer",
    company: "Swaniawski-Jacobi",
    jobLocation: "Al Masallamiyya",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-09-19T22:27:43Z",
  },
  {
    title: "Data Coordinator",
    company: "Mohr, Boyle and Feest",
    jobLocation: "Santa Ana",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-05-19T04:26:24Z",
  },
  {
    title: "Statistician II",
    company: "Moore-Friesen",
    jobLocation: "Huancheng",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-03-16T04:03:46Z",
  },
  {
    title: "Food Chemist",
    company: "Macejkovic, Harris and Blanda",
    jobLocation: "Soldato-Aleksandrovskoye",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-03-22T18:36:53Z",
  },
  {
    title: "Media Manager III",
    company: "Buckridge, Turner and Shanahan",
    jobLocation: "Lebowakgomo",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-01-11T05:06:23Z",
  },
  {
    title: "Safety Technician III",
    company: "Lakin, Beahan and Schaden",
    jobLocation: "Basa",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2024-03-20T13:45:09Z",
  },
  {
    title: "Sales Associate",
    company: "Moen-Robel",
    jobLocation: "Kafyr-Kumukh",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-07-04T08:18:57Z",
  },
  {
    title: "Legal Assistant",
    company: "Howe Group",
    jobLocation: "Sinabang",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2023-12-03T11:31:22Z",
  },
  {
    title: "Structural Analysis Engineer",
    company: "Beahan Group",
    jobLocation: "Agrela",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-03-22T19:59:23Z",
  },
  {
    title: "Senior Quality Engineer",
    company: "McKenzie, Rath and Kovacek",
    jobLocation: "Damiku",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-08-12T07:37:20Z",
  },
  {
    title: "VP Marketing",
    company: "Hirthe and Sons",
    jobLocation: "Novopokrovka",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2023-11-19T12:31:01Z",
  },
  {
    title: "Financial Advisor",
    company: "Lockman, Rice and Bosco",
    jobLocation: "Las Palmas",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-02-18T11:41:53Z",
  },
  {
    title: "Teacher",
    company: "Harris, Sporer and Cruickshank",
    jobLocation: "Zbytków",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-07-26T18:05:35Z",
  },
  {
    title: "Actuary",
    company: "Jacobson Group",
    jobLocation: "Shizuishan",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-04-25T00:37:36Z",
  },
  {
    title: "Data Coordinator",
    company: "Hackett-Reichel",
    jobLocation: "Jembatandua",
    jobType: "full-time",
    jobStatus: "pending",
    createdAt: "2024-05-12T04:34:36Z",
  },
  {
    title: "Quality Engineer",
    company: "Upton-Olson",
    jobLocation: "Mezinovskiy",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-10-09T02:30:11Z",
  },
  {
    title: "Librarian",
    company: "Johns Inc",
    jobLocation: "Yinxi",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-07-28T08:29:44Z",
  },
  {
    title: "Professor",
    company: "Conn-Schimmel",
    jobLocation: "Zeguo",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-01-08T22:20:48Z",
  },
  {
    title: "Electrical Engineer",
    company: "Brown-Corwin",
    jobLocation: "Chatan",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2023-12-14T18:04:22Z",
  },
  {
    title: "Media Manager IV",
    company: "Bruen, Torp and Reinger",
    jobLocation: "Mufushan",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-06-02T10:09:10Z",
  },
  {
    title: "Environmental Tech",
    company: "Ferry, Sipes and Kertzmann",
    jobLocation: "Fresno",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-01-25T20:55:15Z",
  },
  {
    title: "VP Marketing",
    company: "Langworth, Cole and Wuckert",
    jobLocation: "Várzea",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-05-12T18:35:04Z",
  },
  {
    title: "Project Manager",
    company: "Hessel, Lemke and Spencer",
    jobLocation: "Gedera",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-06-24T21:05:02Z",
  },
  {
    title: "Recruiting Manager",
    company: "Kemmer, O'Kon and Wintheiser",
    jobLocation: "Patrocínio",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-02-05T22:51:21Z",
  },
  {
    title: "Help Desk Operator",
    company: "Tremblay, Walsh and Stark",
    jobLocation: "Murakami",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2023-12-03T15:12:24Z",
  },
  {
    title: "Senior Sales Associate",
    company: "Swaniawski and Sons",
    jobLocation: "Alīābad",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2024-05-10T06:01:29Z",
  },
  {
    title: "Media Manager II",
    company: "Hoeger-Kuhn",
    jobLocation: "Ermidas do Sado",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-02-13T01:39:04Z",
  },
  {
    title: "Executive Secretary",
    company: "Farrell-Rippin",
    jobLocation: "Ailibugai",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-01-17T19:55:29Z",
  },
  {
    title: "Paralegal",
    company: "Hudson-Jast",
    jobLocation: "Tagbacan Ibaba",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2023-12-19T15:30:46Z",
  },
  {
    title: "Senior Quality Engineer",
    company: "Pouros, Pollich and Greenholt",
    jobLocation: "Kashihara-shi",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-10-12T17:20:28Z",
  },
  {
    title: "Data Coordinator",
    company: "Kuhlman, Schuster and Fisher",
    jobLocation: "Sinazongwe",
    jobType: "part-time",
    jobStatus: "rejected",
    createdAt: "2024-07-16T09:58:51Z",
  },
  {
    title: "Tax Accountant",
    company: "Padberg and Sons",
    jobLocation: "Phutthaisong",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-02-12T07:38:03Z",
  },
  {
    title: "Computer Systems Analyst III",
    company: "Zemlak Inc",
    jobLocation: "Kopang Satu",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-07-09T14:29:32Z",
  },
  {
    title: "Quality Control Specialist",
    company: "Quitzon-Bogan",
    jobLocation: "Xueshan",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-03-17T12:00:57Z",
  },
  {
    title: "Marketing Assistant",
    company: "Zemlak and Sons",
    jobLocation: "Qŭrghontepa",
    jobType: "full-time",
    jobStatus: "interview",
    createdAt: "2024-05-18T20:02:15Z",
  },
  {
    title: "Programmer II",
    company: "Gislason, Boyer and Kutch",
    jobLocation: "Alburitel",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-07-25T17:38:35Z",
  },
  {
    title: "Senior Editor",
    company: "Gutkowski-Cruickshank",
    jobLocation: "Krousón",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2024-08-25T20:56:56Z",
  },
  {
    title: "Technical Writer",
    company: "Miller, Gulgowski and Thompson",
    jobLocation: "Slutsk",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2024-01-02T15:43:22Z",
  },
  {
    title: "Chief Design Engineer",
    company: "Johns-Botsford",
    jobLocation: "Chaparral",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-08-20T23:13:23Z",
  },
  {
    title: "Data Coordinator",
    company: "Hahn Inc",
    jobLocation: "Naga",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2024-06-08T15:11:12Z",
  },
  {
    title: "Senior Cost Accountant",
    company: "Jacobson-Schneider",
    jobLocation: "Gryfino",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-09-13T06:08:57Z",
  },
  {
    title: "Staff Accountant II",
    company: "Christiansen and Sons",
    jobLocation: "Dongyuan",
    jobType: "internship",
    jobStatus: "rejected",
    createdAt: "2024-03-02T12:10:02Z",
  },
  {
    title: "Software Engineer III",
    company: "Crooks-Cremin",
    jobLocation: "Stockholm",
    jobType: "part-time",
    jobStatus: "interview",
    createdAt: "2024-01-02T12:23:13Z",
  },
  {
    title: "VP Marketing",
    company: "Davis Inc",
    jobLocation: "Montpellier",
    jobType: "full-time",
    jobStatus: "rejected",
    createdAt: "2023-11-01T12:09:13Z",
  },
  {
    title: "Web Designer II",
    company: "Graham, Cummings and Reinger",
    jobLocation: "Deba Habe",
    jobType: "internship",
    jobStatus: "pending",
    createdAt: "2024-08-31T03:30:55Z",
  },
  {
    title: "Director of Sales",
    company: "Koss, Green and Bergstrom",
    jobLocation: "Wangcheng",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-08-20T19:41:42Z",
  },
  {
    title: "Web Designer I",
    company: "Jenkins-Friesen",
    jobLocation: "Pepayan",
    jobType: "part-time",
    jobStatus: "pending",
    createdAt: "2024-04-28T22:11:26Z",
  },
  {
    title: "Help Desk Technician",
    company: "Fay LLC",
    jobLocation: "Limoges",
    jobType: "internship",
    jobStatus: "interview",
    createdAt: "2024-08-02T18:39:44Z",
  },
];
